### ISSUE TITLE
Provide a mechanism for dumping schemas of all events (and transitively included classes)

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-safer-serializer#31]
Related to #28.

This would be priceless for detecting (esp. inadvertent) changes in events for the given PR in CI pipeline.

Possibly one of the serializers (kryo? borer?) already provides this functionality - pls research. 

If not, then let's consider a Scala compiler plugin again (it could even just extract Scala source code of events and transitively included classes from the codebase).

**Comment by MarconZet** [comment]
I have research Kryo and Borer. Kryo does everything at runtime. As expected, it doesn't know anything about classes it will serialise. Borer also doesn't keep its information in a central place. It's impossible to collect all codecs with certainty.

**Comment by MarconZet** [comment]
@PawelLipski
Maybe instead of compiler plugin, sbt task would be more appropriate? Either way, I doubt we can do it with something else than the compiler plugin (or maybe custom compiler, like the one in checker-plugin/test?), as we at least need AST to traverse through (which can be achieved with ANTLR, but that would be too much of a hassle).
